model:
  policy_model:
    ckpt: /code/FineGrainedRLHF/tasks/qa_feedback/model_outputs/t5-small-full-train/best
    input_padding_side: right
    train_generation_kwargs:
      do_sample: True
      top_k: 20
      top_p: null
      temperature: 0.7
    eval_generation_kwargs:
      do_sample: False
      num_beams: 1
  value_model:
    ckpt: /code/FineGrainedRLHF/ModelSets/t5-base
    freeze_value_model: False
    policy_value_sharing: False
  

reward:
  # model_types: ["relevance", "factuality", "completeness"]
  # model_types: []
  model_types: ["factuality"]
  # model_types: ["relevance"]
  # model_types: ["completeness"]

  relevance_model:
    ckpt: /code/FineGrainedRLHF/tasks/qa_feedback/model_outputs/rel_rm/50epoch_onstep2/model_step_80_f1_0.534_acc_0.565
    positive_reward: 0.3
    negative_reward: -0.3
    load_model: False
  eval_relevance_model:
    ckpt: /code/FineGrainedRLHF/ModelSets/rel_rm_best
    positive_reward: 0.3
    negative_reward: -0.3
    load_model: False

  factuality_model:
    ckpt: /code/FineGrainedRLHF/tasks/qa_feedback/model_outputs/fact_rm/selectSet_step/model_step_2_f1_0.087_acc_0.638
    positive_reward: 0.5
    negative_reward: -0.5
    load_model: True
  eval_factuality_model:
    ckpt: /code/FineGrainedRLHF/ModelSets/fact_rm_best
    positive_reward: 0.5
    negative_reward: -0.5
    load_model: True

  completeness_model:
    ckpt: /code/FineGrainedRLHF/tasks/qa_feedback/model_outputs/SelectSet_rm-FN/comp_rm/model_epoch_25.594405594405593_acc_0.670
    mean: -0.44677690555995353
    std: 8.301160619054132
    bias: 0.0
    scale: 0.3
    load_model: False
  eval_completeness_model:
    ckpt: /code/FineGrainedRLHF/ModelSets/comp_rm_best
    mean: -0.44677690555995353
    std: 8.301160619054132
    bias: 0.0
    scale: 0.3
    load_model: False


env:
  max_input_len: 1024
  max_generated_len: 200
  train_num_samples_per_input: 4

ppo:
  kl_coef: 0.3
  lam: 0.95
  gamma: 1.0
  pg_coef: 1.0
  vf_coef: 1.0
  cliprange: 0.2
  cliprange_value: 0.2
  whiten_rewards: True
  sep: </s>

train:
  total_episodes: 80000
  eval_interval: 200
  sampling_batch_size_per_card: 8
  training_batch_size_per_card: 4
  lr: 0.00001
  n_warmup_steps: 100
  n_ppo_epoch_per_rollout: 4
  kl_threshold: 10.0
  clip_grad: False
  max_grad_norm: 0.5
  seed: 42
  cuda_deterministic: True

logging:
  run_name: 1（Test）fact_rm_step_2_f1_0.087_acc_0.638
  # run_name: 2（Test）rel_rm_step_80_f1_0.534_acc_0.565
  wandb_log: True
  wandb_entity: battam
  # wandb_project: T5-small_RM_research
  wandb_project: T5-small_RM_research_StepTest_StepOnly
  log_interval: 1
  save_dir: tasks/qa_feedback/model_outputs/fact_RLHF_T5-small-step_steponly/T5-small-full_fact_rm_step_2_f1_0.087_acc_0.638
  # save_dir: tasks/qa_feedback/model_outputs/rel_RLHF_T5-small-step_steponly/T5-small-full_rel_rm_step_80_f1_0.534_acc_0.565